# 热部署
spring.devtools.restart.enabled: true

server:
    port: 27080
    servlet.context-path: /
    
# redis 
spring.redis.host: 192.168.56.180
spring.redis.port: 6379  
spring.redis.password: ys123
